# Generated by Django 5.2.7 on 2025-10-16 18:56

import apps.common.file_path
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_rooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('pets_allowed', models.BooleanField(default=False)),
                ('country', models.CharField(default='Germany', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('has_air_conditioning', models.BooleanField(default=None, null=True)),
                ('has_tv', models.BooleanField(default=None, null=True)),
                ('has_minibar', models.BooleanField(default=None, null=True)),
                ('has_fridge', models.BooleanField(default=None, null=True)),
                ('has_kitchen', models.BooleanField(default=None, null=True)),
                ('has_bathroom', models.BooleanField(default=None, null=True)),
                ('has_washing_machine', models.BooleanField(default=None, null=True)),
                ('has_hair_dryer', models.BooleanField(default=None, null=True)),
                ('hygiene_products', models.BooleanField(default=None, null=True)),
                ('has_parking', models.BooleanField(default=None, null=True)),
                ('distance_to_center', models.FloatField(blank=True, null=True)),
                ('distance_to_sea', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=apps.common.file_path.image_listing_upload_to)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=apps.common.file_path.image_listing_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
